version: '3.1'

services:
  bd_alpha_sports:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bd_alpha_sports
      MYSQL_ROOT_USER: root
      MYSQL_USER: joss
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: D